# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PowerTools-Upload-File
version:      0.02
version_from: lib/PowerTools/Upload/File.pm
installdirs:  site
requires:
    File::Scan::ClamAV:            

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
